#!/bin/bash -e

function install_mpc_dependencies() {
  installdir="$1"
  install-local install gmp 5.1.2
}

function install_mpc() {
  version="$1"
  installdir="$2"
  setup_file="${installdir}/setup.sh"
  srcdir="$(pwd)/mpc-${version}"
  tarball="mpc-${version}.tar.gz"
  download_url="http://www.multiprecision.org/mpc/download/${tarball}"

  # TODO:
  # install-local use mpfr 3.1.2 --silent | while read setup_cmd; do
  #   echo "${setup_cmd}"
  #   eval ${setup_cmd}
  #   which autoconf
  #   installdir="${installdir}/mpfr/3.1.2"
  # done

  debug__ "version=${version}"
  debug__ "installdir=${installdir}"
  debug__ "setup_file=${setup_file}"
  debug__ "srcdir=${srcdir}"
  debug__ "tarball=${tarball}"
  debug__ "download_url=${download_url}"
 
  #-------------------------------------------------------------------------------
  # Download and unpack
  #-------------------------------------------------------------------------------
  if [ ! -f "$tarball" -a ! -f "${tarball}" ]; then
      echo "[INFO] Downloading MPC '$download_url'"
      wget --verbose "$download_url" || exit 1
  else
      echo "[INFO] [SKIP] MPC tarball already exists: '$tarball'"
  fi
  
  if [ ! -d "$srcdir" ]; then
      echo "[INFO] Unpacking MPC tarball: '$tarball'"
      tar xzvf "${tarball}"
  else
      echo "[INFO] [SKIP] MPC source code already exists: '$srcdir'"
  fi
  
  #-------------------------------------------------------------------------------
  # Build and install
  #-------------------------------------------------------------------------------
  cd "${srcdir}"
  
  if [ ! -e "${installdir}/lib" ]; then
      echo "[INFO] Configuring MPC"
      echo "[INFO] Installing to '$installdir'"
  
      "${srcdir}/configure" --prefix="$installdir" --with-gmp="${GMP_HOME}" --with-mpfr="${MPFR_HOME}" || exit 1
  
      make -j all || exit 1
      make -j install || exit 1
  fi
  
      echo "[INFO] Creating MPC environment setup file ${setup_file}"
      cat > "${setup_file}" <<-EOF
#!/bin/bash
#
# Automatically generated by $0 on $(date)

# TODO:
$(install-local use mpfr 3.1.2 --silent)

export MPC_VERSION="${version}"
export MPC_HOME="${installdir}"
export LD_LIBRARY_PATH="\${MPC_HOME}/lib:\${LD_LIBRARY_PATH}"
EOF
}

