#!/bin/bash -e

function install_gcc_dependencies() {
  installdir="$1"
  install-local install mpc 1.0
}

function install_gcc() {
  version="$1"
  installdir="$2"
  setup_file="${installdir}/setup.sh"
  srcdir="$(pwd)/gcc-${version}"
  tarball="gcc-${version}.tar.gz"
  download_url="http://www.netgull.com/gcc/releases/gcc-${version}/${tarball}"

  # TODO:
  languages="c,c++,fortran"

  install_gcc_dependencies "${installdir}"

  # TODO:
  # install-local use mpc 1.0 --silent | while read setup_cmd; do
  #   echo "${setup_cmd}"
  #   eval ${setup_cmd}
  #   which autoconf
  #   installdir="${installdir}/mpc/1.0"
  # done

  debug__ "version=${version}"
  debug__ "installdir=${installdir}"
  debug__ "setup_file=${setup_file}"
  debug__ "srcdir=${srcdir}"
  debug__ "tarball=${tarball}"
  debug__ "download_url=${download_url}"
 
  #-------------------------------------------------------------------------------
  # Download and unpack
  #-------------------------------------------------------------------------------
  if [ ! -f "$tarball" ]; then
      echo "[INFO] Downloading GCC '$download_url'"
      wget --verbose "$download_url" || exit 1
  else
      echo "[INFO] [SKIP] GCC tarball already exists: '$tarball'"
  fi
  
  if [ ! -d "$srcdir" ]; then
      echo "[INFO] Unpacking GCC tarball: '$tarball'"
      tar xzvf "${tarball}"
  else
      echo "[INFO] [SKIP] GCC source code already exists: '$srcdir'"
  fi
  
  #-------------------------------------------------------------------------------
  # Build and install
  #-------------------------------------------------------------------------------
  cd "${srcdir}"
  
  if [ ! -e "${installdir}/bin" ]; then
      echo "[INFO] Configuring GCC"
      echo "[INFO] Installing to '$installdir'"
  
      # TODO: --disable-multilib
      CFLAGS="-I/usr/include/x86_64-linux-gnu" \
          "${srcdir}/configure" \
              --prefix="$installdir" \
              --enable-languages="${languages}" \
              --disable-multilib \
              --with-gmp="${GMP_HOME}" \
              --with-mpfr="${MPFR_HOME}" \
              --with-mpc="${MPC_HOME}" || exit 1
  
      make -j${INSTALL_LOCAL_PARALLELISM} all || exit 1
      make -j${INSTALL_LOCAL_PARALLELISM} install || exit 1
  fi
  
      echo "[INFO] Creating GCC environment setup file ${setup_file}"
      cat > "${setup_file}" <<-EOF
#!/bin/bash
#
# Automatically generated by $0 on $(date)

# TODO:
$(install-local use mpc 1.0 --silent)

export GCC_VERSION="${version}"
export GCC_HOME="${installdir}"
export PATH="\${GCC_HOME}/bin:\${PATH}"
export LD_LIBRARY_PATH="\${GCC_HOME}/lib:\${LD_LIBRARY_PATH}"
EOF
}

