#!/usr/bin/env bash
#
# Summary: Output command to add a specific tool to your environment
#
# Usage: install-local use [--usage] TOOL VERSION
#
# Output command to add a specific tool to your environment

set -e
[ -n "$INSTALL_LOCAL_TRACE" ] && set -x

function use_tool__() {
  tool="$1" version="$2" prefix="${tool}/${version}" installdir="${INSTALL_LOCAL_DESTDIR}/${prefix}"

  if ! setup_file="$(find "${installdir}/setup.sh" 2>/dev/null)"; then
    info__ "[FATAL] ${tool} ${version} is not installed. Aborting..."
    exit 1 
  else
    info__ "Usage: ${tool} ${version}"
    info__ 
    info__ "    $ source ${setup_file}"
  fi
}

use_tool__ "$@"

