#!/usr/bin/env bash
#
# Summary: Install a specific tool
#
# Usage: install-local install [--usage] TOOL VERSION
#
# Auto-magically installs TOOL and its dependencies.

set -e
[ -n "$INSTALL_LOCAL_TRACE" ] && set -x

function install_tool__() {
  tool="$1" version="$2" prefix="${tool}/${version}" installdir="${INSTALL_LOCAL_DESTDIR}/${prefix}" workspace="${INSTALL_LOCAL_TMPDIR}/${prefix}"

  if test -z "${tool}"; then
    info__ "tool name was not specified"
    install-local help install
    exit 1
  elif test -z "${version}"; then
    info__ "${tool} version was not specified"
    install-local help install
    exit 1
  elif test -z "${prefix}"; then
    info__ "installation \$prefix was not specified"
    exit 1
  elif test -z "${installdir}"; then
    info__ "\$installdir was not specified"
    exit 1
  elif test -z "${workspace}"; then
    info__ "\$workspace was not specified"
    exit 1
  else
    install-local has "${tool}" "${version}"
  fi


  info__ "Preparing to install ${tool} ${version} to ${installdir} using workspace ${workspace}"
  source "${INSTALL_LOCAL_TOOLS}/${prefix}/install.sh"

  mkdir -p "${workspace}"
  pushd    "${workspace}"

  install_${tool} ${version} ${installdir}

  popd

  install-local use "${tool}" "${version}"

  # Enable once tests and safeguards are in place;
  # just to avoid unintended rm -rf catastrophes ;-)
  : rm -rf "${workspace}"
}

install_tool__ "$@"

