#!/usr/bin/env bash
#
# Summary: Install a specific tool
#
# Usage: install-local install [--usage] TOOL
#
# Auto-magically installs TOOL and its dependencies.

set -e
[ -n "$INSTALL_LOCAL_TRACE" ] && set -x

function install_tool__() {
  tool="$1" version="$2" prefix="${tool}/${version}" installdir="${INSTALL_LOCAL_DESTDIR}/${prefix}" workspace="${INSTALL_LOCAL_TMPDIR}/${prefix}"

  info__ "Preparing to install ${tool} ${version} to ${installdir} using workspace ${workspace}"
  source "${INSTALL_LOCAL_TOOLS}/${prefix}/install.sh"

  mkdir -p "${workspace}"
  pushd    "${workspace}"
  
  install_${tool}_dependencies ${installdir}
  install_${tool} ${version} ${installdir}

  popd

  # Enable once tests and safeguards are in place;
  # just to avoid unintended rm -rf catastrophes ;-)
  : rm -rf "${workspace}"
}

install_tool__ "$@"

