#!/usr/bin/env bash
# Inspiration from nodenv 
# CLI inspiration, check bats

: ${INSTALL_LOCAL:="$(dirname "$0")/.."}
: ${INSTALL_LOCAL_DESTDIR:="${HOME}/.install-local"}
: ${INSTALL_LOCAL_TOOLS:="${INSTALL_LOCAL}/tools"}
: ${INSTALL_LOCAL_TMPDIR:="/tmp"}
: ${INSTALL_LOCAL_DEBUG:="false"}
: ${INSTALL_LOCAL_TRACE:=}
export INSTALL_LOCAL
export INSTALL_LOCAL_DESTDIR
export INSTALL_LOCAL_TMPDIR
export INSTALL_LOCAL_TOOLS
export INSTALL_LOCAL_DEBUG

source "${INSTALL_LOCAL}/lib/colors.bash" || exit 1

export PATH="${INSTALL_LOCAL}/libexec:${PATH}"

#source "${INSTALL_LOCAL}/lib/preexec.bash" || exit 1
#function preexec (){
#  printf "${echo_green}[install-local]${normal} "
#}
#preexec_interactive_mode=yes
#preexec_install || exit 1

function info__() {
  echo "[INFO] $@"
}

function debug__() {
  if test "x${INSTALL_LOCAL_DEBUG}" = "xtrue" || \
     test "x${INSTALL_LOCAL_DEBUG}" = "xyes";
  then
      echo "[DEBUG] $@"
  fi
}

export -f info__
export -f debug__

#------------------------------------------------------------------------------
# Install-Local API
#------------------------------------------------------------------------------

function process_cli__() {
  command="$1"
  case "${command}" in
    "" | "-h" | "--help" )
        echo -e "$(install-local-help)" >&2
        ;;
    "-v" | "--version" )
        exec install-local-version
        ;;
    * )
        command_path="$(command -v "install-local-${command}" || true)"
        if [ -z "${command_path}" ]; then
            echo "install-local: no such command \'${command}'" >&2
            exit 1
        fi

        shift 1
        exec "${command_path}" "$@"
        ;;
  esac
}

function start_main__() {
  process_cli__ $@
}

start_main__ $@

