#!/bin/bash -e

function install_autoconf_dependencies() {
  installdir="$1"
}

function install_autoconf() {
  version="$1"
  installdir="$2"
  setup_file="${installdir}/setup.sh"
  srcdir="$(pwd)/autoconf-${version}"
  tarball="autoconf-${version}.tar.xz"
  download_url="http://ftp.gnu.org/gnu/autoconf/${tarball}"

  echo "version=${version}"
  echo "installdir=${installdir}"
  echo "setup_file=${setup_file}"
  echo "srcdir=${srcdir}"
  echo "tarball=${tarball}"
  echo "download_url=${download_url}"

  #-------------------------------------------------------------------------------
  # Install dependencies
  #-------------------------------------------------------------------------------
  install_autoconf_dependencies "${installdir}"
 
  #-------------------------------------------------------------------------------
  # Download and unpack
  #-------------------------------------------------------------------------------
  if [ ! -f "$tarball" -a ! -f "${tarball%.xz}" ]; then
      echo "[INFO] Downloading Autoconf '$download_url'"
      wget --verbose "$download_url" || exit 1
  else
      echo "[INFO] [SKIP] Autoconf tarball already exists: '$tarball'"
  fi
  
  if [ ! -d "$srcdir" ]; then
      echo "[INFO] Unpacking Autoconf tarball: '$tarball'"
      unxz "$tarball" || exit 1
      tar xvf "${tarball%.xz}"
  else
      echo "[INFO] [SKIP] Autoconf source code already exists: '$srcdir'"
  fi
  
  #-------------------------------------------------------------------------------
  # Build and install
  #-------------------------------------------------------------------------------
  cd "${srcdir}"
  
  if [ ! -e "${installdir}/bin" ]; then
      echo "[INFO] Configuring Autoconf"
      echo "[INFO] Installing to '$installdir'"
  
      "${srcdir}/configure" --prefix="$installdir" || exit 1
  
      make -j all || exit 1
      make -j install || exit 1
  fi
  
      echo "[INFO] Creating Autoconf environment setup file ${setup_file}"
      cat > "${setup_file}" <<-EOF
#!/bin/bash
#
# Automatically generated by $0 on $(date)
export version="${version}"
export AUTOCONF_HOME="${installdir}"
export PATH="\${AUTOCONF_HOME}/bin:\${PATH}"
EOF
}

