#!/bin/bash -e

function install_mpfr_dependencies() {
  installdir="$1"
  install-local install gmp 5.1.2
}

function install_mpfr() {
  version="$1"
  installdir="$2"
  setup_file="${installdir}/setup.sh"
  srcdir="$(pwd)/mpfr-${version}"
  tarball="mpfr-${version}.tar.gz"
  download_url="http://ftp.gnu.org/gnu/mpfr/${tarball}"

  debug__ "version=${version}"
  debug__ "installdir=${installdir}"
  debug__ "setup_file=${setup_file}"
  debug__ "srcdir=${srcdir}"
  debug__ "tarball=${tarball}"
  debug__ "download_url=${download_url}"

  #-------------------------------------------------------------------------------
  # Install dependencies
  #-------------------------------------------------------------------------------
  install_mpfr_dependencies "${installdir}"
  # TODO:
  # install-local use mpfr 5.1.2 --silent | while read setup_cmd; do
  #   echo "${setup_cmd}"
  #   eval ${setup_cmd}
  #   which autoconf
  #   installdir="${installdir}/mpfr/5.1.2"
  # done
 
  #-------------------------------------------------------------------------------
  # Download and unpack
  #-------------------------------------------------------------------------------
  if [ ! -f "$tarball" -a ! -f "${tarball}" ]; then
      echo "[INFO] Downloading MPFR '$download_url'"
      wget --verbose "$download_url" || exit 1
  else
      echo "[INFO] [SKIP] MPFR tarball already exists: '$tarball'"
  fi
  
  if [ ! -d "$srcdir" ]; then
      echo "[INFO] Unpacking MPFR tarball: '$tarball'"
      tar xzvf "${tarball}"
  else
      echo "[INFO] [SKIP] MPFR source code already exists: '$srcdir'"
  fi
  
  #-------------------------------------------------------------------------------
  # Build and install
  #-------------------------------------------------------------------------------
  cd "${srcdir}"
  
  if [ ! -e "${installdir}/lib" ]; then
      echo "[INFO] Configuring MPFR"
      echo "[INFO] Installing to '$installdir'"
  
      "${srcdir}/configure" --prefix="$installdir" --with-gmp="${GMP_HOME}" || exit 1
  
      make -j all || exit 1
      make -j install || exit 1
  fi
  
      echo "[INFO] Creating MPFR environment setup file ${setup_file}"
      cat > "${setup_file}" <<-EOF
#!/bin/bash
#
# Automatically generated by $0 on $(date)

# TODO:
$(install-local use gmp 5.1.2 --silent)

export MPFR_VERSION="${version}"
export MPFR_HOME="${installdir}"
export LD_LIBRARY_PATH="\${MPFR_HOME}/lib:\${LD_LIBRARY_PATH}"
EOF
}

